---
title: "Untitled"
author: "Anu Yetukuri"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read Data

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)

#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Clean Data

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything for KNN and ANN
tele_norm <- as.data.frame(lapply(telemm, normalize))
```
# Test and Train 
## We are using a 60% proportion to build our model
```{r}
# 70 - 30 split
set.seed(12345)
nrow(telemm)
```
```{r}
tele_prop <- 0.7
train_tele <- sample(1:nrow(telemm),tele_prop*nrow(telemm))
tele_train <- telemm[train_tele, ]
tele_test <- telemm[-train_tele, ]
```

# Build Model 1
## Model 1 is a base model that includes all remaining predictor variables.
```{r}

tele_logistic <- glm(yyes ~., data = tele_train, family = "binomial")
summary(tele_logistic)
```

# Predict 1

```{r}
telepred <-predict(tele_logistic, tele_test, type = "response")
telepred01 <- ifelse (telepred >= 0.5, 1, 0)
summary(telemm)
```

## Evaluate 1
```{r}
library(caret)
confusionMatrix(as.factor(telepred01), as.factor(tele_test$yyes), positive = "1")


```
## Build Model 2: Stepwise 
```{r}
tele_step <- __(telemm)
```



























## Getting Train and Test Samples

```{r}
# Selects 10000 random rows for test data
set.seed(12345)
test_set <- sample(1:nrow(telemm), 10000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the yyes column
tele_train <- telemm[-test_set, -match("yyes",names(telemm))]
tele_test <- telemm[test_set, -match("yyes",names(telemm))]

#Now the response (aka Labels) - only the yyes column
tele_train_labels <- telemm[-test_set, "yyes"]
tele_test_labels <- telemm[test_set, "yyes"]
```

## Build Model 
```{r}
telemm_logistic <- glm(yyes~., data = telemm, family = "binomial")
summary(telemm_logistic)
```

## Predict Model 
```{r}
logpred <-predict(telemm_logistic , , type = "response")
m1pred01 <- ifelse (m1pred >= 0.5, 1, 0)
summary(m1)
```

