---
title: "Tele_Project_ANN"
author: "Fishbowlz"
date: "2023-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Call Libraries
```{r}
library(dplyr)
library(caret)
library(neuralnet)
library(class)
```


```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)
str(tele)
```

# Clean Data
```{r}
#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)
```

```{r}
#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything for KNN and ANN
tele_norm <- as.data.frame(lapply(telemm, normalize))
```

# Building ANN
## Split Data Into Test and Train
We are using a 70% proportion to build our model
```{r}
# 70 - 30 split
set.seed(12345)

tele_prop <- 0.7
train_tele <- sample(1:nrow(telemm),tele_prop*nrow(telemm))
tele_train <- telemm[train_tele, ]
tele_test <- telemm[-train_tele, ]

# normalized data is needed for ANN and KNN
train_tele_norm <- sample(1:nrow(tele_norm),tele_prop*nrow(tele_norm))
tele_norm_train <- tele_norm[train_tele_norm, ]
tele_norm_test <- tele_norm[-train_tele_norm, ]

```

## Build Model

```{r}
#tele_norm_train$yyes
# simple ANN with only a single hidden neuron
tele_ann_model <- neuralnet(formula = `yyes` ~ .,
                              data = tele_norm_train, hidden = c(3,2,2), linear.output = FALSE, stepmax=1e6)

# visualize the network topology
plot(tele_ann_model)
```

```{r}
plot(tele_ann_model)
```


### Predict and Evaluate ANN Model

```{r}
tele_ann_pred <- predict(tele_ann_model, tele_norm_test)

tele_ann_pred_bin <- ifelse(tele_ann_pred >= 0.5, 1, 0)

confusionMatrix(as.factor(tele_ann_pred_bin), as.factor(tele_norm_test$yyes), positive = as.character(1))
```

## Write Predictions
```{r}
write.csv(tele_ann_pred_bin, "tele_ann_pred_output.csv")
```

