---
title: "Tele-Project"
author: "Maxym Wolberg"
date: "2023-10-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Get Data

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)
str(tele)
```
# Clean Data
```{r}
#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything for KNN and ANN
tele_norm <- as.data.frame(lapply(telemm, normalize))
```

## Creating Clusters

```{r}

tele_norm_no_y <- tele_norm[,-53]
tele_clusters <- kmeans(tele_norm_no_y, 7)
tele_clusters$size

tele_clusters$centers

tele_norm$cluster <- tele_clusters$cluster

tapply(tele_norm$yyes, tele_norm$cluster, mean, na.rm = T)

#Found number of successful calls
0.23599493*7890 + 0.35957121*3265
# Calculated total number of calls
7890+3265
# found percent of successful calls
3036/11155
# Successful calls (profit)
(3036*(10-1)) - ((11155 - 3036)*2)

```